{% set version = "2.7-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pls
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pls_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pls/pls_{{ version }}.tar.gz
  sha256: 8f1d960ab74f05fdd11c4c7a3d30ff9e263fc658f5690b67278ca7c045d0742c

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('pls')"           # [not win]
    - "\"%R%\" -e \"library('pls')\""  # [win]

about:
  home: http://mevik.net/work/software/pls.html, https://github.com/bhmevik/pls
  license: GPL-2.0-only
  summary: Multivariate regression methods Partial Least Squares Regression (PLSR), Principal Component Regression (PCR) and Canonical Powered Partial Least Squares (CPPLS).
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pls
# Title: Partial Least Squares and Principal Component Regression
# Version: 2.7-1
# Date: 2019-03-23
# Authors@R: c(person("Bjrn-Helge", "Mevik", role = c("aut", "cre"), email = "b-h@mevik.net"), person("Ron", "Wehrens", role = "aut"), person("Kristian Hovde", "Liland", role = "aut"), person("Paul",  "Hiemstra", role = "ctb"))
# Author: Bjrn-Helge Mevik [aut, cre], Ron Wehrens [aut], Kristian Hovde Liland [aut], Paul Hiemstra [ctb]
# Maintainer: Bjrn-Helge Mevik <b-h@mevik.net>
# Encoding: UTF-8
# LazyData: yes
# Description: Multivariate regression methods Partial Least Squares Regression (PLSR), Principal Component Regression (PCR) and Canonical Powered Partial Least Squares (CPPLS).
# Depends: R (>= 2.10)
# Imports: grDevices, graphics, methods, stats
# Suggests: MASS, parallel, Rmpi, testthat, RUnit
# License: GPL-2
# URL: http://mevik.net/work/software/pls.html, https://github.com/bhmevik/pls
# BugReports: https://github.com/bhmevik/pls/issues
# NeedsCompilation: no
# Packaged: 2019-03-23 17:32:09 UTC; bhm
# Repository: CRAN
# Date/Publication: 2019-03-23 18:00:03 UTC
