travis:
  secure:
    BINSTAR_TOKEN: KZSEShQKc8DtdNCQ8upixEPO5rG7nus9Bv4szSAL501NWbgh7upyszLZpaL5C+HCm6TFbmfFcgwchTKE4u9zNL3tfCMBaeKXgLmw9nztDd4dc07/5GREvU84GxmFH4EMl/voFUgbL/54WuDQ3/kfUK46KREeyXljH1CnB8bL7Mrs75O8fH28dEOQ/JHGRg98sdT1jXk0MV2u8SoTi5TcEpmlU6ruv1wjpF4OXwSN6LbvOny3PutLlGvtduWaC/kXUYuosarm48LoclhxEYW0tsbOjkSmcsb1R0Re9A4M+/7QE4GlhF3nsZdKD4gTn1MeC9OqzIvsryYL1Vtw25J4bvlvyk3fa5a0ApqnxXvw/KfLcpvHfPFuvA/e4q9Zen1CM/TCE5iL7AElZRUY6t8pA7JoYX9UneS++uBHkFWSwPWCsaYMtgMnNy3VlNnCAZjWyv7EgnBFOOs2Ajf4I+QKBnNsx1zvFlvpuWRSXZXzQtYbqdTlyPOgJVscvS1WjF1jjOzDvCSY6v0eDYxVaOMs5wZx5oNpxv47NRa2WXG/MbyjNjElrLh8I6JH34LFHZ8tOrrhq4zN5MExEWVJjBon98BJ8m04c+VI7g/oFEuQGJR/Ce6B11lYmUzZHAPDV9LOI7DeIdpKZQahqcZ9hWVawTo/Y60EJQJS/7d2FJEf3oQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
